/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2018-01-19 04:23:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class newticket_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>New Ticket</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("    <!-- jQuery library -->\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("    <!-- Latest compiled JavaScript -->\r\n");
      out.write("    <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <header>\r\n");
      out.write("        <nav class=\"navbar navbar-default\">\r\n");
      out.write("            <div class=\"container-fluid\">\r\n");
      out.write("                <div class=\"navbar-header\">\r\n");
      out.write("                    <a class=\"navbar-brand\" href=\"#\">Agile Management</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <ul class=\"nav navbar-nav\">\r\n");
      out.write("                    <li class=\"active\"><a href=\"#\">Dashboard</a></li>\r\n");
      out.write("                    <li><a href=\"ticket.html\">Tickets</a></li>\r\n");
      out.write("                    <li><a href=\"ticket.html\">Sprints</a></li>\r\n");
      out.write("                    <li><a href=\"#\">Projects</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </header>\r\n");
      out.write("    <ul class=\"dashboard clearfix\">\r\n");
      out.write("        <li class=\"divider-2\">\r\n");
      out.write("            <a href=\"#\" class=\"dash-title\"></a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"divider-2\">\r\n");
      out.write("            <a href=\"project.html\" class=\"dash-title cs-btn\" style=\"margin-left: 150px;\"><i class=\"fa fa-arrow-left icon-style\"></i>Back to Results</a>\r\n");
      out.write("        </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-1\"></div>\r\n");
      out.write("            <div class=\"col-md-8\">\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"usr\">Subject</label>\r\n");
      out.write("                    <input type=\"text\" placeholder=\"Enter a brief introduction for this ticket\" class=\"form-control\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"comment\">Message (optional)</label>\r\n");
      out.write("                    <textarea class=\"form-control\" placeholder=\"Enter the body of this ticket\" rows=\"5\"></textarea>\r\n");
      out.write("                </div>\r\n");
      out.write("                <ul class=\"nav nav-tabs\">\r\n");
      out.write("                    <li class=\"active\"><a data-toggle=\"tab\" href=\"#home\">Properties</a></li>\r\n");
      out.write("                    <li><a data-toggle=\"tab\" href=\"#menu2\">Progress & Deadlines</a></li>\r\n");
      out.write("                    <li><a data-toggle=\"tab\" href=\"#menu3\">Attachments</a></li>\r\n");
      out.write("                    <li><a data-toggle=\"tab\" href=\"#menu4\">Tags</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <div class=\"tab-content\">\r\n");
      out.write("                    <div id=\"home\" class=\"tab-pane fade in active\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-md-2\">\r\n");
      out.write("                                <label for=\"\">Status</label>\r\n");
      out.write("                                <div class=\"dropdown\">\r\n");
      out.write("                                    <!--  <button class=\"btn btn-primary dropdown-toggle\" type=\"button\" data-toggle=\"dropdown\" style=\"width: 120px; border:none;margin-top: 20px;\">New\r\n");
      out.write("                                        <span class=\"caret\"></span></button> -->\r\n");
      out.write("                                    <select class=\"btn-style\" style=\"width: 120px;padding: 7px 10px; border:none;margin-top: 20px;>\r\n");
      out.write("                                        <option value=\" Accepted \">Accepted</option>\r\n");
      out.write("                                        <option value=\"In progress \">In progress</option>\r\n");
      out.write("                                        <option value=\"Completed \">Completed</option>\r\n");
      out.write("                                        <option value=\"Invalid \">Invalid</option>\r\n");
      out.write("                                    </select>    \r\n");
      out.write("                                    <!-- <ul class=\"dropdown-menu \">\r\n");
      out.write("                                        <li><a href=\"# \">Accepted</a></li>\r\n");
      out.write("                                        <li><a href=\"# \">In progress</a></li>\r\n");
      out.write("                                        <li><a href=\"# \">Completed</a></li>\r\n");
      out.write("                                        <li><a href=\"# \">Invalid</a></li>\r\n");
      out.write("                                    </ul> -->\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-2 \">\r\n");
      out.write("                                <label for=\" \">Priority</label>\r\n");
      out.write("                                <div class=\"dropdown \">\r\n");
      out.write("                                    <!-- <button class=\"btn btn-primary dropdown-toggle \" type=\"button \" data-toggle=\"dropdown \" style=\"width: 120px; border:none;margin-top: 20px; \">New\r\n");
      out.write("                                        <span class=\"caret \"></span></button> -->\r\n");
      out.write("                                    <select class=\"btn-style \" style=\"width: 120px;padding: 7px 10px; border:none;margin-top: 20px;\">\r\n");
      out.write("                                        <option value=\"Normal\">Normal</option>\r\n");
      out.write("                                        <option value=\"Critical\">Critical</option>\r\n");
      out.write("                                        <option value=\"High\">High</option>\r\n");
      out.write("                                        <option value=\"Low\">Low</option>\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                    <!--                                     <ul class=\"dropdown-menu\">\r\n");
      out.write("                                        <li><a href=\"#\">Normal</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">Critical</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">High</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">Low</a></li>\r\n");
      out.write("                                    </ul> -->\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-2\">\r\n");
      out.write("                                <label for=\"\">Category</label>\r\n");
      out.write("                                <div class=\"dropdown\">\r\n");
      out.write("                                    <!--                                     <button class=\"btn btn-primary dropdown-toggle\" type=\"button\" data-toggle=\"dropdown\" style=\"width: 120px; border:none;margin-top: 20px;\">New\r\n");
      out.write("                                        <span class=\"caret\"></span></button> -->\r\n");
      out.write("                                    <select class=\"btn-style\" style=\"width: 120px;padding: 7px 10px; border:none;margin-top: 20px;\">\r\n");
      out.write("                                        <option value=\" API \">API</option>\r\n");
      out.write("                                        <option value=\"Cosmetic \">Cosmetic</option>\r\n");
      out.write("                                        <option value=\"General \">General</option>\r\n");
      out.write("                                        <option value=\"Refactoring \">Refactoring</option>\r\n");
      out.write("                                    </select>      \r\n");
      out.write("<!--                                     <ul class=\"dropdown-menu \">\r\n");
      out.write("                                        <li><a href=\"# \">API</a></li>\r\n");
      out.write("                                        <li><a href=\"# \">Cosmetic</a></li>\r\n");
      out.write("                                        <li><a href=\"# \">General</a></li>\r\n");
      out.write("                                        <li><a href=\"# \">Refactoring</a></li>\r\n");
      out.write("                                    </ul> -->\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-2 \">\r\n");
      out.write("                                <label for=\" \">Ticket Type</label>\r\n");
      out.write("                                <div class=\"dropdown \">\r\n");
      out.write("                                     <select class=\"btn-style \" style=\"width: 120px;padding: 7px 10px; border:none;margin-top: 20px;\">\r\n");
      out.write("                                        <option value=\"Feature\">Feature</option>\r\n");
      out.write("                                        <option value=\"Bug\">Bug</option>\r\n");
      out.write("                                        <option value=\"Enhancement\">Enhancement</option>\r\n");
      out.write("                                        <option value=\"Task\">Task</option>\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                    <!--                                     <ul class=\"dropdown-menu\">\r\n");
      out.write("                                        <li><a href=\"#\">Feature</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">Bug</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">Enhancement</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">Task</a></li>\r\n");
      out.write("                                    </ul> -->\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-2\">\r\n");
      out.write("                                <label for=\"\">Assigned User</label>\r\n");
      out.write("                                <div class=\"dropdown\">\r\n");
      out.write("                                    <select class=\"btn-style\" style=\"width: 120px;padding: 7px 10px; border:none;margin-top: 20px;\">\r\n");
      out.write("                                        <option value =\"User\">User</option>\r\n");
      out.write("                                    </select> \r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div id=\"menu1\" class=\"tab-pane fade \">\r\n");
      out.write("                        <div class=\"dropdown \">\r\n");
      out.write("                            <button class=\"btn btn-primary dropdown-toggle \" type=\"button \" data-toggle=\"dropdown \" style=\"width: 120px;border: none;margin-top: 20px; \">New\r\n");
      out.write("                                <span class=\"caret \"></span></button>\r\n");
      out.write("                            <ul class=\"dropdown-menu \">\r\n");
      out.write("                                <li><a href=\"# \">Accepted</a></li>\r\n");
      out.write("                                <li><a href=\"# \">In progress</a></li>\r\n");
      out.write("                                <li><a href=\"# \">Completed</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div id=\"menu2\" class=\"tab-pane fade \">\r\n");
      out.write("                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. In, temporibus, accusamus! Architecto eos recusandae ipsum velit exercitationem alias dolores nam.</p>\r\n");
      out.write("                        <ul class=\"clearfix \">\r\n");
      out.write("                            <li class=\"divider-2 \">\r\n");
      out.write("                                <label>Start date</label>\r\n");
      out.write("                                <input type=\"date\">\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"divider-2 \">\r\n");
      out.write("                                <label>End date</label>\r\n");
      out.write("                                <input type=\"date\">\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                        <div class=\"bg clearfix \">\r\n");
      out.write("                            <a  href=\"ticket.html \">\r\n");
      out.write("                                <button class=\"btn btn-success btn-sm \">Update Post</button>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div id=\"menu3\" class=\"tab-pane fade \">\r\n");
      out.write("                        <label>File Upload</label>\r\n");
      out.write("                        <input type=\"file\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div id=\"menu4\" class=\"tab-pane fade \">\r\n");
      out.write("                        <h3>Users</h3>\r\n");
      out.write("                        <input type=\"checkbox\">\r\n");
      out.write("                        <span>UserName</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-1 \"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <footer>\r\n");
      out.write("        <ul class=\"foot-content \">\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"# \">Blog</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"# \">Twitter</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"# \">Terms & Conditions</a>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </footer>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
