/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2018-01-19 09:26:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class project_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>agile</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("<!-- jQuery library -->\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("<!-- Latest compiled JavaScript -->\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("\t<script>\r\n");
      out.write("   \t\t history.forward();\r\n");
      out.write("\t</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<header>\r\n");
      out.write("\t\t<nav class=\"navbar navbar-default\">\r\n");
      out.write("\t\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t\t\t<a class=\"navbar-brand\" href=\"#\">Agile Management</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"ticket.html\">Tickets</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"ticket.html\">Sprints</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Projects</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\" class=\"user\"><i class=\"fa fa-user\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t");

								session.getAttribute("email");
							
      out.write("</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<ul class=\"dashboard clearfix\">\r\n");
      out.write("\t\t<li class=\"divider-2\"><a href=\"#\" class=\"dash-title\">Create\r\n");
      out.write("\t\t\t\tNew Project</a></li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-1 col=sm-12\"></div>\r\n");
      out.write("\t\t\t<div class=\"col-md-7 col=sm-12 left-content\">\r\n");
      out.write("\t\t\t\t<p class=\"auth\">Lorem ipsum dolor sit amet, consectetur\r\n");
      out.write("\t\t\t\t\tadipisicing elit. Omnis provident vero sapiente sunt, animi\r\n");
      out.write("\t\t\t\t\taccusantium culpa quaerat neque consequuntur iste?</p>\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" placeholder=\"Enter a name for this Project\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"form-control\" id=\"pwd\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<span>How do you manage your workflow?</span>\r\n");
      out.write("\t\t\t\t<div class=\"radio lab-title\">\r\n");
      out.write("\t\t\t\t\t<label> <input type=\"radio\" name=\"optradio\">Traditional\r\n");
      out.write("\t\t\t\t\t\t- Tickets are added to milestones to track the project progress\r\n");
      out.write("\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"radio\">\r\n");
      out.write("\t\t\t\t\t<label> <input type=\"radio\" name=\"optradio\">Agile -\r\n");
      out.write("\t\t\t\t\t\tTickets area added to time boxed sprints to plan upcoming work and\r\n");
      out.write("\t\t\t\t\t\treviews\r\n");
      out.write("\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"bg clearfix\">\r\n");
      out.write("\t\t\t\t\t<a href=\"ticket.html\">\r\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-success btn-sm\">Create project</button>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-3 col=sm-12\">\r\n");
      out.write("\t\t\t\t<h4>Project Limit</h4>\r\n");
      out.write("\t\t\t\t<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.\r\n");
      out.write("\t\t\t\t\tFugit ipsa ducimus odit libero earum id, itaque laborum accusamus\r\n");
      out.write("\t\t\t\t\tconsequuntur, obcaecati!</p>\r\n");
      out.write("\t\t\t\t<div class=\"bar clearfix\">\r\n");
      out.write("\t\t\t\t\t<span>20</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-1 col=sm-12\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<footer>\r\n");
      out.write("\t\t<ul class=\"foot-content\">\r\n");
      out.write("\t\t\t<li><a href=\"#\">Blog</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">Twitter</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">Terms & Conditions</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
